sudo: required

language: minimal

branches:
  only:
  - master
  - c++-17

services:
  - docker

install:
  - docker build -t bog-dan-ro/getodac .

script:
  - docker run bog-dan-ro/getodac /code/build_test.sh
